### PR TITLE
pull createReactNativeComponentClass

### PR DESCRIPTION
**Pull request by DerayGa**
pull createReactNativeComponentClass

### CODE REVIEW

**Comment by magicismight** [comment]
Thx for this PR
:+1:

**Comment by chunghe** [comment]
after react v0.25.0, `createReactNativeComponentClass` must import from 'react/lib/createReactNativeComponentClass', please see my pull request https://github.com/magicismight/react-native-svg/commit/4af7dc664b5db8feb5bc4bab2b65639f829d1905

so this pull request will cause problems for users using react-native v0.25.0 or above.

@magicismight please consider bumping major version since it's a breaking change and allow react-native 0.24.0, 0.25.0 users continue using your great work.

**Comment by magicismight** [comment]
@chunghe 
Thx for this useful suggestion.
I`ll find a way to work this out for both 0.25.0 above an 0.24.0

**Comment by magicismight** [comment]
It`s totally a mess after the dependencies changed after 0.25.0 !
I`ll fix this later.
Have to change lots of code to work this out.

**Comment by marcshilling** [comment]
Is this broken again in React Native 0.26.0? `createReactNativeComponentClass` is no longer under `react-native/Libraries/ReactNative/`

**Pull request merged**
